% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Anàlisis de dades òmiques: PEC1},
  pdfauthor={Gabriel Regueira Huguet},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Anàlisis de dades òmiques: PEC1}
\author{Gabriel Regueira Huguet}
\date{2025-03-27}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{ABSTRACT}\label{abstract}

L'objectiu d'aquest estudi ha estat aprendre la funcionalitat de
l'objecte \emph{SummarizedExperiment} i familiaritzar-se amb la ruta
d'un anàlisi exploratori de dades metabolòmiques. Per fer-ho, s'ha
utilitzat un dataset provinent d'un estudi que analitzava perfils
metabolòmics de diferents concentracions de metabòlits en la orina de
pacients amb \emph{Cachexia} o pacients control. Aquest dataset amb 77
pacients i 63 metabòlits mesurats s'ha reorganitzat mitjançant l'objecte
de classe \emph{SummarizedExperiment} per a fer-ne posteriorment un
anàlisi exploratori. L'anàlisi exploratori ha inclòs anàlisis
univariants (Boxplots, Boxplots múltiples) i anàlisis multivariants
(PCA, Clustering jeràrquic i Heatmap), utilitzant eines no paramètriques
perquè les dades no seguien una distribució normal (tests de Wilcoxon).
Els resultats han mostrat diferències estadísticament significatives en
les concentracions de la majoria de metabòlits entre ambdós grups,
suggerint que aquest perfil metabolòmic podria tenir un paper important
en la identificació de pacients amb \emph{cachexia}.

\section{OBJECTIUS}\label{objectius}

Els objectius d'aquest informe són familitaritzar-se amb la ruta d'un
anàlisis de dades metabolòmiques, desde la seva importació de dades
crues fins al posterior anàlisis exploratori estadístic i interpretació
dels resultats. Per a això, serà necessari un seguit de sub-objectius:

\begin{itemize}
\tightlist
\item
  Familiaritzar-se amb l'OOP S4 \emph{SummarizedExperiment}
  (Bioconductor, 2024) i crear-ne un amb les dades que s'han triat.
\item
  Aprendre a utilitzar el repositori github per fer control de versions
  git, acabant amb un repositori de Github contenint els materials
  necessaris per a clonar tota la informació de l'estudi.
\item
  Indagar en les dades per trobar patrons mitjançant el llenguatge de
  programació R i familiaritzar-se amb els preprocessats de dades
  necessaris i mètodes que s'utilitzen per fer un anàlisis estadístic
  exploratori de dades metabolòmiques.
\end{itemize}

\section{MÈTODES}\label{muxe8todes}

Per a fer aquesta PEC1 s'han utilitzat un conjunt de dades provinents
d'un estudi sobre pacients amb càncer, que inclou concentracions de 63
metabòlits diferents en mostres d'orina expressades en \(\mu\)M. i
informació clínica sobre pacients amb \emph{cachexia} i pacients
control. Les dades es van importar en format \emph{.csv} des del
repositori de GitHub proporcionat per l'enunciat de la PEC1. Mitjançant
el programa RStudio, es van importar les dades a través de l'url del
mateix repositori i es va estructurar l'informació en un objecte de
classe \emph{SummarizedExperiment}, integrant la matriu de dades
quantitatives i les metadades clíniques de cada pacient. L'anàlisis
exploratori estadístic va incloure un estudi univariant (resums
numèrics, boxplots i tests de \emph{Wilcoxon}) i un estudi multivariant
mitjançant un anàlisis de components principals (PCA). Seguint amb la
exploració de dades, es va realitzar un clustering jeràrquic i un
heatmap per identificar patrons de similitud entre les mostres. Tots els
anàlisis es van realitzar mitjançant el programa RStudio i el llenguatge
de programació d'R.

\section{RESULTATS}\label{resultats}

\textbf{Url repositori GitHub:}
\url{https://github.com/Gabrirehu/Regueira-Huguet-Gabriel-PEC1.git}

\subsection{1- Seleccionem un dataset de
metabolòmica:}\label{seleccionem-un-dataset-de-metaboluxf2mica}

La \emph{cachexia} és un síndrome metabòlic complex, que es mostra
habitual en pacients amb càncer. Aquest síndrome es caracteritza per una
pèrdua de massa muscular i/o greixosa, inflamació sistèmica, alteracions
hormonals i en el metabolisme enegètic. Aquesta pèrdua de massa muscular
es tradueix a un catabolisme muscular accelerat, que proboca
l'alliberament de aminoàcids com la valina, leucina, alanina, etc.
Aquest síndrome proboca que el pacient es trobi en un estat de semi-fam
metabòlica, que proboca que hi hagi una demanda energètica elevada i
alguns metabòlits intermedis del metabolisme energètic s'acumulen
(3-hydrpxybutyrate, pyroglutamate, glutamine).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Importem directament les dades crues (raw) desde el repositori de github que proporciona l\textquotesingle{}enunciat:}
\NormalTok{url\_github }\OtherTok{\textless{}{-}} \StringTok{"https://raw.githubusercontent.com/nutrimetabolomics/metaboData/refs/heads/main/Datasets/2024{-}Cachexia/human\_cachexia.csv"} 
\NormalTok{human\_cachexia\_data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(url\_github, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{sep =} \StringTok{","}\NormalTok{) }\CommentTok{\#Separació per comes tal i com estàn organitzades les dades crues}
\end{Highlighting}
\end{Shaded}

Observem un dataset on les files són les mostres (pacients) i les
columnes són els metabòlits analitzats. També podem observar que hi ha
una variable que separa els pacients en dos grups, pacients amb
\emph{cachexia} i pacients control.

\subsection{\texorpdfstring{2- Crear un objecte
\emph{SumarizedExperiment}:}{2- Crear un objecte SumarizedExperiment:}}\label{crear-un-objecte-sumarizedexperiment}

Per a crear un objecte \emph{SummarizedExperiment} necessito una matriu
de dades quantitatives (amb les concentracions de metabòlits per
pacient) i un \emph{colData} amb informació de les mostres, que en
aquest cas és el tipus de grup que pertany cada pacient
(\emph{Muscle.loss: cachexia/control}).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Matriu de dades numèriques}
\NormalTok{assay\_data1\_ }\OtherTok{\textless{}{-}}\NormalTok{ human\_cachexia\_data[, }\SpecialCharTok{{-}}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{)] }\CommentTok{\#Eliminem les dues primeres columnes (mostres i grup)}
\FunctionTok{rownames}\NormalTok{(assay\_data1\_) }\OtherTok{\textless{}{-}}\NormalTok{ human\_cachexia\_data}\SpecialCharTok{$}\NormalTok{Patient.ID }\CommentTok{\#Assignem com a nom de fila els identificadors Patient.ID en el dataset}
\NormalTok{assay\_data1 }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(assay\_data1\_)}
\FunctionTok{View}\NormalTok{(assay\_data1) }\CommentTok{\#Observem que tenim el nom de les files assignats als identificadors dels pacients (Patient.ID) i les colmunes son els metabòlits}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#colData: Informació sobre les mostres (pacients): Muscle.loss}
\NormalTok{col\_data1 }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Patient.ID =}\NormalTok{ human\_cachexia\_data}\SpecialCharTok{$}\NormalTok{Patient.ID, }\CommentTok{\#Agafem els pacients,}
  \AttributeTok{Muscle.loss =}\NormalTok{ human\_cachexia\_data}\SpecialCharTok{$}\NormalTok{Muscle.loss }\CommentTok{\#I el grup al que pertanyen}
\NormalTok{)}
\FunctionTok{rownames}\NormalTok{(col\_data1) }\OtherTok{\textless{}{-}}\NormalTok{ human\_cachexia\_data}\SpecialCharTok{$}\NormalTok{Patient.ID }\CommentTok{\#Assignem coma nom de fila els indentificadors com hem fet amb assay\_data}
\FunctionTok{View}\NormalTok{(col\_data1) }
\end{Highlighting}
\end{Shaded}

Abans de fer el \emph{SummarizedExperiment}, necessitem tenir una matriu
numèrica on les mostres estiguin com a columnes en comptes de com a
files, de la mateixa manera els metabòlits com a files en comptes de com
a columnes:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Trasposem la matriu per tenir metabolits (files) x pacients (columnes)}
\NormalTok{assay\_data1t }\OtherTok{\textless{}{-}} \FunctionTok{t}\NormalTok{(assay\_data1)}
\FunctionTok{View}\NormalTok{(assay\_data1t) }\CommentTok{\#Automàticament ja cambia rownames per colnames quan trasposem la matriu}
\end{Highlighting}
\end{Shaded}

Ara ja tenim la matriu de dades numèriques llesta per a fer
\emph{SummarizedExperiment}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(SummarizedExperiment)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cachexia\_se }\OtherTok{\textless{}{-}} \FunctionTok{SummarizedExperiment}\NormalTok{(}
  \AttributeTok{assays =} \FunctionTok{list}\NormalTok{(}\AttributeTok{counts =}\NormalTok{ assay\_data1t), }\CommentTok{\#Matriu de dades }
  \AttributeTok{colData =}\NormalTok{ col\_data1 }\CommentTok{\#Grup per pacient}
\NormalTok{)}
\NormalTok{cachexia\_se}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## class: SummarizedExperiment 
## dim: 63 77 
## metadata(0):
## assays(1): counts
## rownames(63): X1.6.Anhydro.beta.D.glucose X1.Methylnicotinamide ...
##   pi.Methylhistidine tau.Methylhistidine
## rowData names(0):
## colnames(77): PIF_178 PIF_087 ... NETL_003_V1 NETL_003_V2
## colData names(2): Patient.ID Muscle.loss
\end{verbatim}

Una vegada creat el \emph{SummarizedExperiment}, el guardarem en un
arxiu en format .Rda com indica l'enunciat:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{save}\NormalTok{(cachexia\_se, }\AttributeTok{file =} \StringTok{"cachexia\_se.rda"}\NormalTok{) }\CommentTok{\#Guardem l\textquotesingle{}arxiu al repositori}
\end{Highlighting}
\end{Shaded}

\subsubsection{\texorpdfstring{Diferències \emph{ExpressionSet} i
\emph{SummarizedExperiment}:}{Diferències ExpressionSet i SummarizedExperiment:}}\label{diferuxe8ncies-expressionset-i-summarizedexperiment}

\emph{ExpressionSet} ha estat durant molt temps el format clàssic per
analitzar dades de miacroarrays, només admet una única matriu de dades
(\emph{exprs}). És molt útil, però està pensat per un tipus específic de
dades i no té tanta flexibilitat. En canvi l'objecte
\emph{SummarizedExperiment} és més potent, ja que és capaç de gestionar
més tipus de dades (comptes, intensitats, etc) i pot contenir múltiples
matrius (en \emph{assays}) i és compatible amb dades més complexes, és
l'OOP estàndard actual per a estudis RNa-seq, proteòmica i metabolòmica.
Tots dos objectes són molt útils per organitzar les dades de manera
integrada i sincronitzada, però \emph{SummarizedExperiment} ho fa amb
més flexibilitat i amb una estructura més moderna.

\subsection{3- Anàlisis exploratori:}\label{anuxe0lisis-exploratori}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#S\textquotesingle{}ha fet un resum estadístic per a cada metabòlit (mínim, mitjana, màxim, etc), posem els 5 primer com a exemple:}
\FunctionTok{apply}\NormalTok{(}\FunctionTok{assay}\NormalTok{(cachexia\_se)[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{, ], }\DecValTok{1}\NormalTok{, summary) }\CommentTok{\#Resum numèric dels metabòlits (5 primers)}
\FunctionTok{dim}\NormalTok{(cachexia\_se)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Comprovem que no hi hagi valors faltants (NA) en la matriu de dades}
\FunctionTok{anyNA}\NormalTok{(}\FunctionTok{assay}\NormalTok{(cachexia\_se))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] FALSE
\end{verbatim}

Podem observar de forma general que aquestes dades consten d'un OOP
\emph{SummarizedExperiment} on la matriu de dades està format per 77
pacients (columnes) els quals estàn dividits pel grup ``Muscle.Loss'' i
63 metabòlits (files) que són les concentracions de diferents metabòlits
analitzades en les mostres d'orina dels pacients.

\subsubsection{Anàlisis univariant:
Creatina}\label{anuxe0lisis-univariant-creatina}

Hem realitzat apart un anàlisi del test \emph{Shapiro-Wilk} per saber si
les variables numèriques (metabòlits) segueixen una distribució normal.
Resulta que cap d'elles segueix una distribució normal i, per tant,
haurem de procedir amb l'anàlisis sense asumir normalitat.

\begin{figure}

{\centering \includegraphics{Gabriel_Regueira_Huguet_PEC1_files/figure-latex/unnamed-chunk-10-1} 

}

\caption{Concentració creatina segons grup}\label{fig:unnamed-chunk-10}
\end{figure}

Fem un test \emph{Wilcoxon} per veure si les distribucions de creatina
són diferents entre grups (\emph{Muscle.loss}), sense assumir
normalitat:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{wilcox.test}\NormalTok{(creatina }\SpecialCharTok{\textasciitilde{}}\NormalTok{ muscle\_loss) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot
## compute exact p-value with ties
\end{verbatim}

\begin{verbatim}
## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  creatina by muscle_loss
## W = 1077, p-value = 0.0001042
## alternative hypothesis: true location shift is not equal to 0
\end{verbatim}

Mitjançant aquest anàlisi bàsic podem observar que el metabòlit creatina
mostra una diferència significativa en la concentració entre els grups
\emph{Muscle.loss}. Observem que la mitjana en el grup que tenen
\emph{cachexia} (pèrdua constant de massa muscular) és significativament
superior a la del grup control. Aquests resultats poden indicar que la
concentració de creatina en la orina podria estar relacionada amb
l'estat de cachexia i, per tant, podria ser un potencial marcador per
ajudar a diagnosticar aquesta malaltia.

\subsubsection{Boxplot múltiple: metabòlits més
rellevants}\label{boxplot-muxfaltiple-metabuxf2lits-muxe9s-rellevants}

Seguidament, seguirem amb l'anàlisis estadístic descriptiu mitjançant un
boxplot múltiple. Com que no podem fer un boxplot dels 63 metabòlits,
farem un test de \emph{Wilcoxon} univariant per a cada metabòlit i
seleccionarem els 4 metabòlits que tinguin p-valors més baixos (més
significació).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{metabolits }\OtherTok{\textless{}{-}} \FunctionTok{assay}\NormalTok{(cachexia\_se) }\CommentTok{\#Assignem metabolits }
\NormalTok{group }\OtherTok{\textless{}{-}} \FunctionTok{colData}\NormalTok{(cachexia\_se)}\SpecialCharTok{$}\NormalTok{Muscle.loss }\CommentTok{\#Assignem group a la variables Muscle.loss }
\CommentTok{\#Fem un test Wilcoxon per cada metabòlit i guardem els p{-}valors dels tests}
\NormalTok{p\_valors }\OtherTok{\textless{}{-}} \FunctionTok{apply}\NormalTok{(metabolits, }\DecValTok{1}\NormalTok{, }\ControlFlowTok{function}\NormalTok{(x) \{}
  \FunctionTok{suppressWarnings}\NormalTok{(}
  \FunctionTok{tryCatch}\NormalTok{(}\FunctionTok{wilcox.test}\NormalTok{(x }\SpecialCharTok{\textasciitilde{}}\NormalTok{ group)}\SpecialCharTok{$}\NormalTok{p.value, }\AttributeTok{error =} \ControlFlowTok{function}\NormalTok{(e) }\ConstantTok{NA}\NormalTok{) }\CommentTok{\#Agafem els p\_valors dels tests de cada metabòlits}
\NormalTok{  )}
\NormalTok{\})}
\CommentTok{\#Ordenem els metabòlits segons els p{-}valors que hagin donat els tests}
\NormalTok{p\_valors\_ordenats }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(p\_valors)}
\NormalTok{top\_metabolits }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(p\_valors\_ordenats) [}\DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{]}
\NormalTok{top\_metabolits}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Quinolinate"         "Glucose"             "Adipate"            
## [4] "N.N.Dimethylglycine"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(p\_valors }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\CommentTok{\#coompta quants són significatius}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 55
\end{verbatim}

Aquests són els metabòlits que han donat més nivell de significació fent
el test no paramètric de \emph{Wilcoxon} segons la variable grup
\emph{Muscle.loss}. Per tant, haurien de ser els que tenen diferències
més significatives de concentracions segons si els pacients tenen
\emph{cachexia} o no. També cal recalcar que, \textbf{dels 63 metabòlits
de l'estudi, 55 metabòlits han donat diferències significatives amb el
test de \emph{Wilcoxon} }. Donat que hi han concentracions motl
diferents entre els metabòlits, apliquem una escala logarítmica per tal
que millor la visualització del \emph{Boxplot múltiple}.

\begin{figure}

{\centering \includegraphics{Gabriel_Regueira_Huguet_PEC1_files/figure-latex/unnamed-chunk-13-1} 

}

\caption{Boxplot múltiple de metabòlits més rellevants}\label{fig:unnamed-chunk-13}
\end{figure}

Aquest gràfic mostra les diferències de concentracions dels 4 metabòlits
que presenten més diferències significatives segons la variable
categórica \emph{Muscle.loss}. Tal i com s'observa en el gràfic, els 4
metabòlits tenen majors concentracions en els individus que presenten la
malaltia \emph{cachexia} que en els individus del grup control.

\subsubsection{Anàlisis de Components Principals
(PCA)}\label{anuxe0lisis-de-components-principals-pca}

Mitjançant aquest tipus d'anàlisis, l'objectiu serà reduïr la dimensió
de les dades i visualitzar si les mostres s'agrupen segons
``Muscle.Loss'' (\emph{cachexia/control}) basant-se en els seus perfils
metabolòmics. Tenint en compte que les concentracions de metabòlits
varien molt, és recomanable estandaritzar (escalar) les dades abans de
fer la PCA, ja que sinó les variables amb majors rangs tindràn més pes.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Primerament, trasposem la matriu de l\textquotesingle{}objecte per tenir les mostres com a files i els metabòlits com a columnes}
\NormalTok{t\_data }\OtherTok{\textless{}{-}} \FunctionTok{t}\NormalTok{(}\FunctionTok{assay}\NormalTok{(cachexia\_se))}
\CommentTok{\#És recomanable escalar les variables quan estàn a diferents escales , en el nostre cas algun metabòlit té concentracions molt més elevades que d\textquotesingle{}altres, per tant escalem:}
\NormalTok{pca\_resultats }\OtherTok{\textless{}{-}} \FunctionTok{prcomp}\NormalTok{(t\_data, }\AttributeTok{scale. =} \ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{summary}\NormalTok{(pca\_resultats)}\SpecialCharTok{$}\NormalTok{importance[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{] }\CommentTok{\#Mostrem els 5 components principals més importants (dels 63PC que surten)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                            PC1      PC2      PC3      PC4      PC5
## Standard deviation     5.04667 2.270128 1.833107 1.747276 1.659056
## Proportion of Variance 0.40427 0.081800 0.053340 0.048460 0.043690
## Cumulative Proportion  0.40427 0.486070 0.539410 0.587870 0.631560
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{var\_explicada }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(pca\_resultats)}\SpecialCharTok{$}\NormalTok{importance[}\DecValTok{2}\NormalTok{, ] }\SpecialCharTok{*} \DecValTok{100} \CommentTok{\#Seleccionem PC1 i PC2}
\end{Highlighting}
\end{Shaded}

Observem en els resultats de l'anàlisis de components principals que els
dos primers ja tenen una variabilitat del \textbf{48.61\%}, que ja es
considera bastant alta. Decidim quedar-nos amb els dos primers
components principals i utilitzarem aquests per a obtenir una
representació de les dades en una dimensió reduïda:

\begin{figure}

{\centering \includegraphics{Gabriel_Regueira_Huguet_PEC1_files/figure-latex/unnamed-chunk-15-1} 

}

\caption{Distribució de les mostres segons PC1 i PC2}\label{fig:unnamed-chunk-15}
\end{figure}

S'ha realitzar un anàlisi de components principals sobre la matriu de
concentracions de metabòlits. Prèviament s'han centrat i escalat les
dades per a evitar que les diferències d'escala entre les variables
afectin l'anàlisi. Els dos primers components principals, com es pot
observar, expliquen gairebé un 50\% de la variànça total (48.6\%).
Observem en el gràfic que les mostres del grup \emph{cachexic}
(vermells) tendeixen a situar-se en valors positius de PC1, mentre que
les mostres \emph{control} (blaus) es concentren en valors al voltant de
zero. Això pot indicar que la variabilitat capturada per PC1 està
relacionada amb les diferències entre els dos grups de
\emph{Muscle.loss}, tot i que hi ha molta superposició entre les mostres
i no es pot veure una diferència clara.

La magnitud de la contribució de cada variable a les PC són els seus
``loadings'' en cada PC. Els autovectors (eigenvectors) associats a la
matriu de covariànça són els loadings, indiquen quina direcció prenen
els nous components i quines variables (metabòlits) contribueixen més.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#creem un data frame amb els "loadings" (magnitud de contribució de cada metabòlit al component principal)}
\NormalTok{pca\_resultats }\OtherTok{\textless{}{-}} \FunctionTok{prcomp}\NormalTok{(t\_data, }\AttributeTok{scale. =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{loadings\_pca }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(pca\_resultats}\SpecialCharTok{$}\NormalTok{rotation) }\CommentTok{\#assignem els loadings}
\NormalTok{loadings\_pca}\SpecialCharTok{$}\NormalTok{metabolit }\OtherTok{\textless{}{-}} \FunctionTok{rownames}\NormalTok{(loadings\_pca)}
\end{Highlighting}
\end{Shaded}

\begin{figure}

{\centering \includegraphics{Gabriel_Regueira_Huguet_PEC1_files/figure-latex/unnamed-chunk-17-1} 

}

\caption{Principals metabòlits que contribueixen a PC1}\label{fig:unnamed-chunk-17}
\end{figure}

Aquest gràfic mostra els 10 metabòlits que més contribueixen a la
variànça capturada pel primer component principal (PC1). Com hem pogut
observar prèviament, el PC1 és el component principal del qual la seva
direcció recull la major part de la variabilitat de les dades, i els
valors \emph{loading} indicarien quina força té cada metabòlit en
definir aquesta direcció. Podem oobservar com la majoria de metabòlits
contribueixen de forma gairebé equitativa a la PC1, destaquem la
\emph{Creatine}, que és la que contribueix més. Això té coherència amb
l'anàlisi anterior, on ja havíem vist que aquest metabòlit mostrava
diferències significatives segons el grup (\emph{cachexia/control}).

\subsubsection{Clustering jeràrquic}\label{clustering-jeruxe0rquic}

El clustering jeràquic és un potent recurs per a l'anàlisis exploratori
de dades, porporcionant mètodes potents i flexibles per descubrir grups
en les dades. Com s'ha mencionat anteriorment, els resultats del test no
paramètric de \emph{Wilcoxon} mostren que 55 dels 63 metabòlits de
l'estudi presenten diferències significatives. Això suggereix que
gairebé totes les variables de l¡estudi contenen informació rellevant
per a la classificació, per tant, es va optar per no filtrar i incloure
tots els metabòlits a l'anàlisis de clustering jeràrquic.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dendextend)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Gabriel_Regueira_Huguet_PEC1_files/figure-latex/unnamed-chunk-19-1.pdf}}
\caption{Clustering jeràrquic segons grups}
\end{figure}

Observem en el dendrograma que hi han dos grups principals, un amb només
una bifurcació i l'altre, que conté gairebé totes les mostres, que té
moltes subdivisions. Dintre del clúster amb més mostres trobem vàries
subdivisions que acaben amb una separació visible entre els dos grups de
pacients. EN conjunt, aquest dendograma pot suggerir que els metabòlits
permeten identificar patrons que diferencien els dos grups
(\emph{cachexia/control}), però aquesta diferenciació no es del tot
clara a causa de la quantitat de subdivisions de clústers i la barreja
de msotres d'ambdós grups dins d'aquestes subdivisions.

\subsubsection{Heatmap}\label{heatmap}

Un heatmap amb 63 variables (meatbòlits) seria massa sorollós i difícil
d'interpretar. Per tant, abans de fer el heatmap farem una selecció
prèvia dels 10 metabòlits (variables) més significatius.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Com ho hem fet anteriorment, ja tenim els p{-}valors ordenats dels metabòlits}
\NormalTok{p\_valors\_ordenats }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(p\_valors)}
\NormalTok{top\_metabolits\_heatmap }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(p\_valors\_ordenats)[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{] }\CommentTok{\#Seleccionem els 10 metabòlits més significatius}
\CommentTok{\#extraim les dades només per als meta\textasciigrave{}+bolits més significatius}
\NormalTok{mat }\OtherTok{\textless{}{-}}\NormalTok{ metabolits[top\_metabolits\_heatmap, ] }\CommentTok{\#10 files (metabòlits) x 77 mostres (pacients)}
\CommentTok{\#Escalem pels metabòlits (mitjana 0, desviació 1)}
\NormalTok{mat\_scaled }\OtherTok{\textless{}{-}} \FunctionTok{t}\NormalTok{(}\FunctionTok{scale}\NormalTok{(}\FunctionTok{t}\NormalTok{(mat))) }\CommentTok{\#trasposem, escalem i tornem a transposar després}
\end{Highlighting}
\end{Shaded}

El heatmap mostratà les mostres (pacients) i els metabòlits, però no sap
quin grup pertany cada mostra. Per tant, hem de fer que el mapa pugui
caracteritzar les mostres segons el grup que pertany, li hem de donar la
informació.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pheatmap}\NormalTok{(mat\_scaled, }\CommentTok{\#Matriu de dades de 10 meatbòlits per 77 mostres (pacients) }
         \AttributeTok{annotation\_col =}\NormalTok{ anotacions, }\CommentTok{\#Afegeix una linea de colors a dalt del mapa indicant si la mostra és cachexic o control}
         \AttributeTok{annotation\_colors =} \FunctionTok{list}\NormalTok{(}
           \AttributeTok{Grup =} \FunctionTok{c}\NormalTok{(}\AttributeTok{cachexic =} \StringTok{"limegreen"}\NormalTok{, }\AttributeTok{control  =}\StringTok{"orange"}\NormalTok{) }\CommentTok{\#Definim el color per cada grup}
\NormalTok{         ),}
         \AttributeTok{scale =} \StringTok{"none"}\NormalTok{, }\CommentTok{\#None, ja hem escalat els valors manualment}
         \AttributeTok{clustering\_distance\_rows =} \StringTok{"euclidean"}\NormalTok{, }\CommentTok{\#Mètode per agrupar metabòlits}
         \AttributeTok{clustering\_distance\_cols =} \StringTok{"euclidean"}\NormalTok{, }\CommentTok{\#Mètode per agrupar mostres }
         \AttributeTok{clustering\_method =} \StringTok{"complete"}\NormalTok{, }\CommentTok{\#clustering jeràrquic}
         \AttributeTok{main =} \StringTok{"Heatmap dels 10 metabòlits més significatius"}\NormalTok{,}
         \AttributeTok{fontsize\_row =} \DecValTok{7}\NormalTok{, }\CommentTok{\#Tamany text dels metabòlits significatius }
         \AttributeTok{fontsize\_col =} \DecValTok{4}\NormalTok{) }\CommentTok{\#Tamany text de les mostres}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Gabriel_Regueira_Huguet_PEC1_files/figure-latex/unnamed-chunk-22-1.pdf}}

Com que hem escalat la matriu de dades dels metabòlits, per cada fila de
metabòlit la mitjana és 0 i la desviació estàndard és 1. D'aquesta
manera la majoria de valors d'un metabòlit queden aprop del 0, però si
hi ha algun valor molt alt comparat amb la mitjana, aquesta destacarà
sobre la resta i mostrarà una coloració més llunyana del blau/blanc i
s'aproparà al vermell. D'aquesta manera, amb el heatmap podem veure
quins valors de metabòlits destaquen sobre la resta.

El dendrograma de dalt mostra com les mostres (pacients) s'agrupen
segons la semblança dels seus perfils metabolòmics, d'aquesta manera
veiem que les mostres de color verd que pertany al grup que té
\emph{cachexia} tendeixen a agrupar-se a la dreta, on es mostren valors
dels metabòlits més elevats que les seves mitjanes (colors allunyats del
blau). Mentre que les mostres de taronja que pertanyen als pacients
control, tendeixen a agrupar-se a l'esquerra, amb perfils metabolòmics
més propers a la mitjana (color blau). Tot i així, observem en l'extrem
esquerre que s'acumulen 5 mostres \emph{cachexia} amb uns metabòlits
molt per sobre de la mitjana.

Com ja havíem vist en els anàlisis anteriors, aquest patró reforça la
idea que els pacients amb \emph{cachexia} semblen presentar perfils
metabolòmics diferenciats, amb concentracions més elevades en diversos
metabòlits rellevants. Si ens fixem, de forma general la majoria de
mostres del grup control presenten metabòlits amb concentracions tirant
més a la normalitat (color blau), mentre que les mostres \emph{cachexia}
observem que els seus metabòlits ja tenen alteracions en la coloració
mostrant mitjanes de concentracions més elevades.

\section{DISCUSSIÓ}\label{discussiuxf3}

Els resultats observats al heatmap i la resta d'anàlisis són consistents
amb la literatura científica sobre el síndroma \emph{cachexia}. Ja que
\emph{cachexia} és un síndrome caracteritzat per una gran desregulació
metabòlica, un augment de la degradació de proteïnes musculars i una
activació de la gluconeogènesi i alteració de les vies energètiques
(Evans et al., 2009; Argilés et al., 2014). Aquests processos catabòlics
provoquen l'alliberament d'aminoàcids al torrent sanguini (valina,
leucina, etc) que podem veure reflectits en els pacients amb
\emph{cachexia} en el heatmap (majors concentracions, colors allunyats
del blau). De la mateixa manera s'observa major presència d'intermedis
com 3-hydroxybutyrate, producte de l'oxidació de lípids en contextos de
dèficit energètic. A més, observem un augment de quilonate que podria
reflectir a l'activació de la via del triptòfan associada a l'estrès
inflamatori i oxidatiu, habitual en pacients amb cachexia (Faeron et
al., 2011).

De la mateixa manera, tot i que no es veu tant al heatmap, podem
observar en l'anàlisis univariant que la \emph{Creatine} també presenta
diferències en les concentracions segons el grup al que pertany el
pacient. Aquests resultats també tenen coherència amb la fisiopatologia
del síndrome, ja que un dels símptomes més rellevants de \emph{Cachexia}
comporta un elevat catabolisme proteic i muscular que es pot traduïr a
un augment de les concentracions extracel·lulars de creatina i, en
conseqüència, un augment en la concentració de creatina en la orina dels
pacients.

\section{CONCLUSIÓ}\label{conclusiuxf3}

L'anàlisi estadístic exploratori que s'ha realitzat sobre les dades
metabolòmiques del dataset \emph{human\_cachexia} ha permès identificar
patrons associats a símptomes del desenvolupament del síndrome
\emph{Cachexia}. Els resultats han mostrat que una gran part dels
metabòlits analitzats en la orina dels pacients presenten diferències
significatives (anàlisi no paramètric) entre pacients amb
\emph{cachexia} i pacients control. Aquests resultats reforcen la
hipòtesi que aquest perfil metabolòmic pot reflectir la identificació
del mateix síndrome analitzant les alteracions en les concentracions
d'aquests metabòlits. Els anàlisis multivariants (PCA, clustering i
HEatmap) van poder ser-nos d'ajuda per a identificar aquests patrons,
mostrant agrupaments de les mostres segons el grup i observant com cada
grup tenia, en general, concentracions de metabòlits diferents. Per
tant, es podria dir que els resultats obtinguts suggereixen que
utilitzar aquest perfil metabolòmic per l'identificació de pacients amb
\emph{cachexia} podria ser una eina molt útil en el futur. Tot i així
caldria aprofundir l'estudi i analitzar la seva aplicabilitat clínica en
medicina.

\textbf{Url repositori GitHub:}
\url{https://github.com/Gabrirehu/Regueira-Huguet-Gabriel-PEC1.git}

\section{REFERÈNCIES}\label{referuxe8ncies}

\begin{itemize}
\item
  Evans, W.J., Morley, J.E., Argilés, J., Bales, C., Baracos, V.,
  Guttridge, D., Jatoi, A., Kalantar-Zadeh, K., Lochs, H., Mantovani,
  G., Marks, D., Mitch, W.E., Muscaritoli, M., Najand, A., Ponikowski,
  P., Rossi Fanelli, F., Schambelan, M., Schols, A., Schuster, M.,
  Thomas, D., Wolfe, R., \& Anker, S.D. (2008). Cachexia: A new
  definition. \emph{Clinical Nutrition}, 27(6), 793--799.
  \url{https://doi.org/10.1016/j.clnu.2008.06.013}
\item
  Fearon, K., Strasser, F., Anker, S.D., Bosaeus, I., Bruera, E.,
  Fainsinger, R.L., Jatoi, A., Loprinzi, C., MacDonald, N., Mantovani,
  G., Davis, M., Muscaritoli, M., Ottery, F., Radbruch, L., Ravasco, P.,
  Walsh, D., Wilcock, A., Kaasa, S., \& Baracos, V.E. (2011). Definition
  and classification of cancer cachexia: An international consensus.
  \emph{The Lancet Oncology}, 12(5), 489--495.
  \url{https://doi.org/10.1016/S1470-2045(10)70218-7}
\item
  Bioconductor (2024). \emph{SummarizedExperiment: SummarizedExperiment
  Container}. Disponible a:
  \url{https://bioconductor.org/packages/release/bioc/html/SummarizedExperiment.html}
\item
  Kassambara, A. (2020). \emph{Practical Guide to Cluster Analysis in R:
  Unsupervised Machine Learning}. Datanovia. Disponible a:
  \url{https://www.datanovia.com/en/lessons/cluster-analysis-in-r/}
\item
  ASP Teaching (2024). \emph{Anàlisi Multivariant de Casos en R}.
  Disponible a: \url{https://aspteaching.github.io/AMVCasos/}
\item
  MixOmics Team (2024). \emph{Multivariate Analysis and Integration of
  Omics Data}. Disponible a:
  \url{https://mixomicsteam.github.io/mixOmics-Vignette/}
\item
  Universitat Oberta de Catalunya (2024). \emph{Exploració multivariant
  de dades òmiques}. Materials docents del Màster Universitari d'Anàlisi
  de Dades, UOC.
\item
  Penet, M.F., Krishnamachary, B., Mironchik, Y., Wildes, F., Poussaint,
  T.Y., Lisok, A., et al.~(2018). Predicting cancer-associated muscle
  wasting from urinary metabolomics. \emph{Metabolomics}, 14(8), 1--13.
  \url{https://doi.org/10.1007/s11306-018-1405-2}
\item
  Kassambara, A. (2017). \emph{HCPC - Hierarchical Clustering on
  Principal Components Essentials}. STHDA. Disponible a:
  \url{https://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/117-hcpc-hierarchical-clustering-on-principal-components-essentials/}
\end{itemize}

\end{document}
